SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

if (NOT XC_COMPILER_PREFIX)
    set(XC_COMPILER_PREFIX arm-linux-gnueabihf)
endif()

if (NOT XC_COMPILER_BIN_PATH)
    set(XC_COMPILER_BIN_PATH /usr/bin)
endif()

SET(CMAKE_C_COMPILER
        ${XC_COMPILER_BIN_PATH}/${XC_COMPILER_PREFIX}-gcc)

SET(CMAKE_CXX_COMPILER
        ${XC_COMPILER_BIN_PATH}/${XC_COMPILER_PREFIX}-g++)

# where is the target environment
SET(CMAKE_FIND_ROOT_PATH
        ${XC_COMPILER_BIN_PATH})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)